#HEROKU
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # atau 'update' kalau kamu ingin schema diupdate otomatis
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}




#
#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/nba_player_stats_2024_2025
#    username: postgres
#    password: A.sdfghjkl12345
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    show-sql: true